### ISSUE TITLE
No `useBreakpointTailwindCSS` function

### ISSUE THREAD

**Issue by hawezo** [pikax/vue-composable#153]
There is a documentation for a [`useBreakpointTailwindCSS`](https://pikax.me/vue-composable/composable/breakpoint/breakpointTailwindCSS.html) function, but it isn't in the distributed package. 

I'm using `vue-composable@^1.0.0-dev.9`, and there is only `useBreakpoint` available (which I doesn't seem to make working, by the way). 

So, what am I missing? Did something not get published to NPM, or did I understand something wrong? 

Thanks!

**Comment by pikax** [comment]
The documentation is based on master, but that feature wasn't release, if you update to the latest 10 `vue-composable@^1.0.0-dev.10` you should get it there :)

Thanks for raising it, I need to publish more often :)

**Comment by hawezo** [comment]
Thanks!
