### ISSUE TITLE
How to leverage useOnScroll and useStorage?

### ISSUE THREAD

**Issue by fer22f** [pikax/vue-composable#158]
I'm trying something like this:

```js
    const div = ref(null);
    const currentScrollTop = useOnScroll(div).scrollTop;
    const scrollTop = useStorage("myKey", currentScrollTop.value).storage;
    onMounted(() => {
      div.value.scrollTop = scrollTop.value;
      watch(() => currentScrollTop.value, () => {
        scrollTop.value = currentScrollTop.value
      }, { lazy: true });
    });
```

But it stops working after shifting component around, the values do seem to work, but it no longer stores stuff into Storage.

**Comment by pikax** [comment]
can you provide an reproducible example? 

From what I can guess, it might be `div` gets reassigned, causing it to stop handing the scroll.

I'm working on a fix if that's the case, if not can you provide that example please?

**Comment by fer22f** [comment]
Yea, it's when the div gets reassigned. Here's a repro:

[![Edit suspicious-snowflake-55plb](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-snowflake-55plb?fontsize=14&hidenavigation=1&theme=dark)

**Comment by pikax** [comment]
@fer22f 

Thanks! 👍 

Actually the error was on the `localStorage` returning an invalid ref.

Now you can change: `useOnScroll(div).scrollTop` directly and it will scroll the div :)

**Comment by fer22f** [comment]
Oh nice, thanks!

Is there a terser way to do it than what I described?

**Comment by pikax** [comment]
Nothing drastically different, just maybe reduce some `.value`

```ts
    const div = ref(null);
    const { scrollTop: currentScrollTop, scrollTopTo } = useOnScroll(div);
    const { storage: scrollTop } = useStorage("myKey", currentScrollTop);
    onMounted(() => {
      // div.value.scrollTop = scrollTop.value;

      currentScrollTop.value = scrollTop.value;
      // or
      scrollTopTo(scrollTop.value);

      watch(
        currentScrollTop,
        scroll => {
          console.log("New value: " + scroll);
          scrollTop.value = scroll;
        },
        { lazy: true }
      );
    });
```

But that's more personal preference that something else
