### ISSUE TITLE
axios client should be configurable

### ISSUE THREAD

**Issue by wulucxy** [pikax/vue-composable#247]
Hi @pikax，I may have my own `axios` instance in the project，I think you have to provide the option to config `axios client`。

**Comment by pikax** [comment]
That's a good idea thanks 👍 

Would you pass your client on the first argument? 

```ts
const {exec} = useAxios(myClient)
```

**Comment by wulucxy** [comment]
@pikax，this is my suggestion:

```
// you can always export useAxios or makeAxios
import useAxios, { makeAxios } from 'vue-composable-axios'

// makeAxios just play a factory function to generate useAxios
const useAxios = makeAxios(axiosClient)

// or you can just use the original useAxios
const { data, error, ....rest } = useAxios(options)
```
so this is just an little change in current `useAxios` method，I would prefer this way.

**Comment by pikax** [comment]
sounds good 👍
