### ISSUE TITLE
useOnResize: update width & height when mounted

### ISSUE THREAD

**Issue by vmihailenco** [pikax/vue-composable#364]
Currently width and height are not updated until window is resized (which may not happen at all). What do you think about using `onMounted` to set initial width & height, e.g. add something similar to https://github.com/pikax/vue-composable/blob/36c8b571365c066cac48d5a689a678f34df91d5f/packages/vue-composable/src/event/onResize.ts#L39-L40

```js
if (!element.value) {
  onMounted(handler)
}
```

What do you think?

**Comment by pikax** [comment]
Makes sense, it should wait for mount if you passing a `ref`
