### ISSUE TITLE
Idea: Cancel the promise when beforeDestroy is triggered

### ISSUE THREAD

**Issue by wizardnet972** [pikax/vue-composable#413]
Idea: Cancel the promise when `beforeDestroy` is triggered.

The most cases (for me) when I use `usePromise`, I was need to cancel the promise/axios when the request took a long time and in meanwhile I navigate to another page.

I think it will be nice if `vue-composable` will support cancellation on `beforeDestory` event by demand.

Something like;
```
usePromise(.., { beforeDestory: true });
```

**Comment by pikax** [comment]
That's possible with `useAxios` and `useFetch`, but as far as I know, you actually stop a promise in javascript. 

But for `axios` and `fetch` that's a great idea 👍

**Comment by wizardnet972** [comment]
@pikax I think its simple just to add "beforeUnmount" option in `useCancellablePromise` and if true then call `cancel` in `onBeforeUnmount`. (check the code bellow, but read the all comment please)

On the other hand, when I use  `useCancellablePromise` with `axios` (not `useAxios`), it cancel the promise but not the request like `CancelToken` does (I still see the request pending in the network tab).

So I wrap with `useApi` function, just to handle the `CancelToken`. And I want when the cancel from `useCancellablePromise` happens, to trigger the `CancelToken` of `axios`. 

The problem is the `promise` got undefined.

I think about two possible solutions to handle the cancel: 
- emit event 
- callback 

* to do `watch` on `cancelled`, is a problem in `ts` files- I found some bug when I use it in ts files (not in the setup function) so it kind a problem for me to use watch.

Maybe you have an idea how to solve this?

checkout the code I written it simulate the problem.

```
import { onBeforeUnmount, watchEffect, watch } from '@vue/composition-api';
import axios from 'axios';

export const useApi = (options) => {
  const CancelToken = axios.CancelToken;
  const source = CancelToken.source();

  const cancelToken = source.token;

  const api = useCancellablePromise(() => axios({ ...options, cancelToken }), { lazy: true });

  console.log({ x: api.promise.value }); // <--- this one is undefined..

  api.promise.value.catch(e => { // <-- so here I got error.. no catch for undefined
    source.cancel();
  });

  return api;
};

export const useLongRequest = () => {
  const { exec, cancel } = useApi({ url: `/api/long` });

  exec().then((r) => {
    console.log({ r });
  });

  onBeforeUnmount(() => {
    cancel();
  });
};
```
