### ISSUE TITLE
Bug: useBreakpointTailwindCSS with custom config is not reactive

### ISSUE THREAD

**Issue by blowsie** [pikax/vue-composable#452]
It seems that there is an issue with the handling or reactivity in the `useBreakpointTailwindCSS` composable when using a custom config.
 
Reproduction:
https://codesandbox.io/s/patient-fast-5nbsz

**Comment by pikax** [comment]
Yes, that's because the current is not able to be resolved because of the usage of the media queries.

It is the same behaviour as when you use `useBreakpoint` with a media query instead of number, you will see I can't resolve the current, since the media queries might be colliding with each other

**Comment by blowsie** [comment]
I guess in my case I was not using media queries so I was expecting the same result.

I'm happy to use `useBreakpoint` and import my config values  manually , but it feels like I should have been able to use `useBreakpointTailwindCSS`

**Comment by pikax** [comment]
Can you create a new issue please, I can get it done :)
