### ISSUE TITLE
Error building with vue3-rc9 and vue cli 4.5.4

### ISSUE THREAD

**Issue by unkn0wn1** [pikax/vue-composable#546]
**[test]$ vue create rt2**

Vue CLI v4.5.4
? Please pick a preset: Default (Vue 3 Preview) ([Vue 3] babel, eslint)

Vue CLI v4.5.4
✨  Creating project in /test/rt2.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

> yorkie@2.0.0 install /test/rt2/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done

> core-js@3.6.5 postinstall /test/rt2/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> ejs@2.7.4 postinstall /test/rt2/node_modules/ejs
> node ./postinstall.js

added 1241 packages from 919 contributors in 37.755s

50 packages are looking for funding
  run `npm fund` for details

🚀  Invoking generators...
📦  Installing additional dependencies...

added 72 packages from 82 contributors in 7.321s

55 packages are looking for funding
  run `npm fund` for details

⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project rt2.
👉  Get started with the following commands:

 $ cd rt2
 $ npm run serve

**[test]$ cd rt2**
**[test]$ npm install @vue-composable/axios**
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /test/rt2/node_modules/@vue-composable/axios/scripts/postinstall.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/test/rt2/node_modules/@vue-composable/axios/scripts/postinstall.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

**Comment by pikax** [comment]
Good catch, thank you.

please use `1.0.0-beta.5` 

Fixed https://github.com/pikax/vue-composable/commit/8f7dab40695798a0039be0acb29b9ff236c2f918
