### ISSUE TITLE
vue-composable doesn't install on docker images like alpine

### ISSUE THREAD

**Issue by fchu** [pikax/vue-composable#585]
Hi there,

I've been seeing this issue when trying to install vue-composable on an alpine docker image:
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /app/node_modules/vue-composable/scripts\postinstall.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/app/node_modules/vue-composable/scripts\postinstall.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
With the following `Dockerfile`:
```dockerfile
FROM node:12.10-alpine as build-stage
WORKDIR /app
COPY package.json ./
RUN npm install
```
and `package.json`:
```json
{
  "name": "error-repro",
  "version": "1.0.0",
  "description": "error repro",
  "author": "fchu",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "vue-composable": "^1.0.0-beta.10"
  }
}
```

However when doing it locally it correctly runs (albeit throws an error since vue itself isn't installed):
```
> vue-composable@1.0.0-beta.10 postinstall /private/tmp/test/node_modules/vue-composable
> node ./scripts/postinstall.js

[vue-composable] Vue is not detected in the dependencies. Please install Vue first.

+ vue-composable@1.0.0-beta.10
```

I suppose maybe something about the postinstall script prevents it from correctly working on certain environments?

**Comment by pikax** [comment]
You need to add either Vue2 or vue3 as a dependency, vue composable doesn't ship with Vue dependency

**Comment by fchu** [comment]
Sorry, I was just trying to provide the minimal reproducible steps.

The issue is not the absence of Vue as a peer dependency, but about the `postinstall` script incorrectly running and crashing on docker image (`node:alpine` specifically):
- on Mac: script run fine (_Expected_ behavior is the warning about Vue being not installed)
- on node:alpine: script crashes and `npm install` exit with error

**Comment by zhbhun** [comment]
I meet same issue.
