### ISSUE TITLE
Tree shaking?

### ISSUE THREAD

**Issue by aparajita** [pikax/vue-composable#586]
This is truly an awesome library, not only for its functionality but also as a great example of the coding paradign the composition API enables.

Have you looked into how well the library tree shakes?

**Comment by aparajita** [comment]
Ah, just saw "with aggressive tree-shaking to keep it light on your end code" in the Readme.

**Comment by pikax** [comment]
Thank you.

> Have you looked into how well the library tree shakes?

If you have webpack or rollup configured to tree-shake, it should extract everything that's not used out-of-box
