### ISSUE TITLE
Is vue-composable IE11 compatible?

### ISSUE THREAD

**Issue by kabforks** [pikax/vue-composable#681]
Hello!

Awesome repo!

Just wondering, is this repo IE11 compatible?

Cheers!

**Comment by pikax** [comment]
Hey, thanks.

There shouldn't be any specific code that prevents IE11 usage (AFAIK) 

I opened the docs https://pikax.me/vue-composable/composable/date/performanceNow.html#methods on IE11 and it's working

**Comment by kabforks** [comment]
Thanks for testing! Clever to just test the docs..

I guess my problem is related to transpiling of some sorts.

**Comment by pikax** [comment]
Please check https://cli.vuejs.org/guide/browser-compatibility.html#browserslist (if you are using vue-cli) and make sure you are transpiling to the correct javascript version for IE11


Feel free to open another issue if any of the composables don't work on IE11 :)
