### ISSUE TITLE
Question: how to clear validation once validation failed?

### ISSUE THREAD

**Issue by userquin** [pikax/vue-composable#722]
Hi, is there a way to clear validation status?

I have a form and I can validate before submit, it will be fine to include a reset.

Great work.

**Comment by pikax** [comment]
The validation status should be cleared on when the user changes the `value`, can you provide more info on your use case? 

I currently don't see how a `clear` would be useful

**Comment by userquin** [comment]
@pikax 

I configure the error on each component, using something similar to material design, a simplified version, so I need to validate and collect errors from each input to show the first one inside its corresponding input.

![imagen](https://user-images.githubusercontent.com/6311119/103783412-fc869080-5038-11eb-9277-0899956c8e44.png)


Each page contains (I have a multi-form page) a set of inputs, and the form has the submit, clear and store (it is a PWA to work offline). The clear button will clear all input values (not using `button type=reset`) and then I need to clear all inputs and its errors.

The problem comes due to the fact that I dont know when to show the errors on each component input because I dont have this info available.

This is beacause I have required fields (99% all of them are required), so when I load data from IndexedDB to load it on valitation object, each $value is $dirty (I do not focus the input just press F5 on page). Then I add an @blur handler to toogle an internal `ref<boolean>`, and then if the entry is (internal_dirty and $anyInvalid) or the $anyInvalid form group then I show the error.

As you can see, $dirty must be set "externally", and then the behavior will be handled from the cliente not from the library, you are out of scope, you dont have access to the UI.

```typescript
<script setup lang="ts>
// some refs, watchers omitted...
// was the input focused
const touched = ref(false)

// wrapper for validation object
const fieldValidation = computed(() => {
  return props.validation[props.fieldName]
})

// touched or $dirty
const dirty = computed(() => {
  return touched.value || fieldValidation.value.$dirty
})

const invalid = computed(() => {
  return fieldValidation.value.$anyInvalid
})

// must show the error?
const error = computed(() => {
  return (dirty.value && invalid.value) ? fieldValidation.value.$errors[0] : null
})

const internalMessage = computed(() => {
  // this will show the red lines below the inputs
  if (error.value)
    return error.value
   // this will show the hints to the user: for exmaple on date input, when typing, the hint will be the format (placeholder)
  if (hint.value)
    return hint.value

  return ''
})

// the user has focused the input
const onBlur = async() => {
  await asyncRaf()
  touched.value = true
  await asyncRaf()
  focused.value = false
}
</script>
```

then in the template:

```html
  <div class="text-field-3" :class="[{ error }]">
    <label class="text-field-3__label" :class="[{ floating }]">
      <span :id="props.fieldName" class="label">
        <template v-if="required">
          {{ props.requiredMark }}&#160;{{ text }}
        </template>
        <template v-else>
          {{ text }}
        </template>
      </span>
      <span class="spanner" />
      <input
        v-model="internalValue"
        type="text"
        :maxlength="max ? `${max}` : null"
        class="text-field-3__input"
        :aria-labelledby="props.fieldName"
        :aria-describedby="`${props.fieldName}-message`"
        :aria-invalid="error ? 'true' : 'false'"
        @focus.passive="onFocus"
        @blur.passive="onBlur"
      >
    </label>
    <div class="text-field-3__ripple" :class="[{ focused }]" />
    <div class="text-field-3__hints">
      <div
        :id="`${props.fieldName}-message`"
        :role="error ? 'alert' : null"
        :aria-hidden="internalMessage ? null : 'true'"
        class="message"
      >
        {{ internalMessage }}
      </div>
      <div class="counter">
        {{ counter }}
      </div>
    </div>
  </div>
```

If we change this line:

```typescript
// touched or $dirty
const dirty = computed(() => {
  return touched.value || fieldValidation.value.$dirty
})
```

with this one:

```typescript
// touched or $dirty
const dirty = computed(() => {
  return fieldValidation.value.$dirty
})
```

then all required fields on entry will appear in red with required (spanish: obligatorio).

**Comment by userquin** [comment]
I dont know if vuelidate has the concept of clearing errors, but if you see for example vee-validate you can do this and more, it is hard and complex but it can be done. 

For example, what about if we need to fill errors from server side response?

**Comment by pikax** [comment]
> The clear button will clear all input values (not using `button type=reset`) and then I need to clear all inputs and its errors.

What does it mean `clear` for the library? Because if you initialise a validation with a prepopulated an required input with `today` and then reset the validation what do you expect the value to be cleared or set to the default `today`? 

This is a bit trickier, because you are using the `validation` as the form controller (instead of validation controller), which it can be used to, but not really intended to do that.

One way to achieve your goal would be replacing the validation controller on `reset`, is a bit drastic, but you have the full control over the validation controller.

```ts

function buildValidation(obj) {
  return useValidation({
    name: {
      $value: obj.name, // or `toRef(obj, 'name') `to keep reactivity
    }
  })
}

let form = ref(buildValidation(editObject));

function reset(){
 form.value = buildValidation(editObject) // resets the whole validation object
}
```

---

> As you can see, $dirty must be set "externally", and then the behavior will be handled from the cliente not from the library, you are out of scope, you dont have access to the UI.

`$dirty` means the value has changed (regardless if it was set to the initial value), what you're doing is treating `$dirty` as `$touched`, `$touched` is not provided because that's directly related with the UI and that would be the user responsibility, but you can provide your own by:

```ts
const form = useValidation({
  name: {
    $value: '',
    $touched: false // this will be available on the template to be used
  }
})

if(form.name.$touched) {
  // 
}
```


---
> I dont know if vuelidate has the concept of clearing errors, but if you see for example vee-validate you can do this and more, it is hard and complex but it can be done.

Do you have a link where I can have a quick look, I skimmed through their docs, but didn't noticed.


> For example, what about if we need to fill errors from server side response?

You can a validator that returns a promise or if is at submission you can use something like.

```ts
const form = useValidation({
  name: {
    $value: '',
    $serverErrors: ''
  }
})

function submit(form){
  saveItem(form.toObject()).catch(e=> {
      if(e.errors.name){ 
        form.$serverError = e.errors.name
      }
  })
}
```


---
Thanks for the code, but still not enough for me to be able to test it quickly, do you mind provide a reproduction on codesandbox or codepen or a full `.vue` file where I can just paste on my playground and test it?

**Comment by userquin** [comment]
@pikax 

You are missing we have a UI, if the user do not touch nothing on the screen, why the library do a validation? I undertand your point of view, but it is not a problem where to put things or where to remove any others.

If I have a form with 200 fields all required, the first time a user enter on the page, the validation cannot take place, or at least control if we can show or hide it. Just with the example, if you put an empty validator object with required fields, we developers, cannot control this: dirty from your point of view is complety diferent from the UI perspective.

We have 2 options: integrate with the UI or just make it mutable.

The links for vee-validate are here (v3 -> vue2):

[Displayable errors](https://baianat.github.io/vee-validate/guide/displaying-errors.html)
[Validation provider - Scoped Slot Data](https://baianat.github.io/vee-validate/guide/validation-provider.html#scoped-slot-data)

The links for vee-validate are here (v4 -> vue3), I dont use it yet:

https://vee-validate.logaretm.com/v4/guide/overview

vee-validate provides the bridge between the UI and the validation, for example, you can see the `touched` status from the validator, what I need to do on each of my components (also adds some more just than dirty).

With version 3, there is no need to do nothing, just I use vee-validate, but for v2, you can see this links:

https://vee-validate.logaretm.com/v2/api/field.html
https://vee-validate.logaretm.com/v2/api/validator.html#methods

Here an example with v2: vee-validate injects $validator to each input, then we can access to its internal fields, and change rules (validations) an refresh its validations at runtime (with your approach, validations are statically on the validator object or can mutate at runtime?):

```javascript
        // check if validator has the fields populated
        const fields = this.$refs[modelField].$validator.fields;
        if (fields) {
          const field = fields.find({
            name: modelField,
            scope
          });
          // check the field is populated
          if (field && typeof field.update === "function") {
            await this.$nextTick();
            field.update({ updated: true, rules });
          }
        }
```

I'll try to build a codepen and link it here.

**Comment by pikax** [comment]
> You are missing we have a UI, if the user do not touch nothing on the screen, why the library do a validation?

If the user doesn't change anything in the UI, the `$dirty` should not be set to `true`, it will remain as `false` until the `$value` is changed. That's should be working


> If I have a form with 200 fields all required, the first time a user enter on the page, the validation cannot take place, or at least control if we can show or hide it. 

The validation will run and it will set `$invalid` to true, because the value is invalid even tho is the initial value, but it won't populate the `$errors`  until it's dirty (eg: `$value` is changed)

> dirty from your point of view is complety diferent from the UI perspective

As I said `dirty` and `touched` are two different things - `useValidation` is not an **UI validation** function, it is a model based validation.

 
 > We have 2 options: integrate with the UI or just make it mutable.
 
 1. I currently have no plans to integrate with UI, not the purpose of this library.
 2. It is already mutable...
 
 ```html
 <template>
  <div>
    <input v-model="form.input.$value" />
    <button @click="updateDirty">reset</button>
    <p>
      {{ form }}
    </p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useValidation } from "vue-composable";

export default defineComponent({
  setup() {
    const form = useValidation({
      input: {
        $value: "1",

        required(v) {
          console.log('v', v)
          return v !== "1";
        },
      },
    });


    const updateDirty = ()=> {
      form.input.$dirty = false
    }


    return {
      form,

      updateDirty
    };
  },
});
</script>
 ```



> The links for vee-validate are here (v3 -> vue2):
> 
> [Displayable errors](https://baianat.github.io/vee-validate/guide/displaying-errors.html)
> [Validation provider - Scoped Slot Data](https://baianat.github.io/vee-validate/guide/validation-provider.html#scoped-slot-data)

Page not found.



> vee-validate provides the bridge between the UI and the validation, for example, you can see the `touched` status from the validator, what I need to do on each of my components (also adds some more just than dirty).

Yes it provides it's own UI components, which I don't plan to ship.


> Here an example with v2: vee-validate injects $validator to each input, then we can access to its internal fields, and change rules (validations) an refresh its validations at runtime (with your approach, validations are statically on the validator object or can mutate at runtime?):

The number of fields available on the form is static, if you create the validation form with 3 fields and 3 validations, it will stay with 3 fields and 3 validations throughout. Is limiting but not that much because the validator runs inside of a watch which tracks the dependencies.

--- 


I still don't understand your use case, for what you're saying it seems you are misusing the library, by creating the validation and assigning the value post creation (not sure if that's the case, but seems from your comments)

**Comment by userquin** [comment]
I'll try to playing with a plain and works as expected. The problem, I have a ton of pages with a ton of inputs, so it is too repetitive, and just create a SFC for each type.

I have the following, I think the problem is in the model of the SFC input:

page > form > custom-input1 + custom-input2....

Each page creates a validator object with custom validations (generic async functions):

```typescript
const factory = (
  firstName: Ref<null | string>,
  secondName: Ref<null | string>,
  firstSurname: Ref<null | string>,
  secondSurname: Ref<null | string>,
  documentType: Ref<null | TipoDocumento>,
  documentNumber: Ref<null | string>,
  birthDate: Ref<null | Date>,
  gender: Ref<null | Genero>,
) => {
  return useValidation({
    primerNombre: {
      $text: 'Primer nombre',
      $max: 30,
      $value: firstName,
      required: {
        $validator(v: null | string) {
          return requiredString(v)
        },
        $message: 'obligatorio',
      },
      max: {
        $validator(v: null | string, context: any) {
          return maxStringLength(context.primerNombre.$max, v)
        },
        $message: 'máx. 30 caracteres',
      },
    },
    segundoNombre: {
      $text: 'Segundo nombre',
      $max: 30,
      $value: secondName,
      max: {
        $validator(v: null | string, context: any) {
          return maxStringLength(context.segundoNombre.$max, v)
        },
        $message: 'máx. 30 caracteres',
      },
    },
   ... more entries here
```

Then on the setup method of the page I just create each ref and then call this factory method:

```typescript
<script setup lang="ts">
import { ref } from 'vue'
import { factory } from '/~/logics/cuestionario/v1/caracterizacion'

const primerNombre = ref(null)
const segundoNombre = ref(null)
const primerApellido = ref(null)
const segundoApellido = ref(null)
const tipoDocumento = ref(null)
const numeroDocumento = ref(null)
const fechaNacimiento = ref(null)
const genero = ref(null)

const form = factory(
  primerNombre,
  segundoNombre,
  primerApellido,
  segundoApellido,
  tipoDocumento,
  numeroDocumento,
  fechaNacimiento,
  genero,
)
const submit = async() => {
  const valid = form.$anyInvalid
  const errors = form.$errors
  console.log(`Form invalid: ${valid} => ${errors}`)
}
</script>
<template>
  <form class="caracterizacion-v1" @submit.prevent="submit">
    <div class="inputs">
      <AppTextField3
        v-model="primerNombre"
        field-name="primerNombre"
        :validation="form"
      />
   ... more inputs
</template>
```
Each custom input has a v-model and it is a wrapper over an input: I use useVModel from `vueuse` and so we have, for example the text field:

```typescript
<script setup lang="ts">
import { defineProps, ref, computed, watch, defineEmit, nextTick } from 'vue'
import { useVModel } from '@vueuse/core'
import { asyncRaf } from '/~/logics/cuestionario/helpers'

const props = defineProps({
  fieldName: {
    type: String,
    required: true,
  },
  validation: {
    type: Object,
    required: true,
  },
  modelValue: {
    type: String,
    required: false,
  },
  requiredMark: {
    type: String,
    default: '(*)',
  },
})
const emit = defineEmit(['update:modelValue'])
const internalValue = useVModel(props, 'modelValue', emit)

const focused = ref(false)
const floating = ref(false)
const touched = ref(false)

const fieldValidation = computed(() => {
  return props.validation[props.fieldName]
})
```
So I thing the problem is `const internalValue = useVModel(props, 'modelValue', emit)` that is the v-model of the input:

```html
      <input
        v-model="internalValue"
        type="text"
        :maxlength="max ? `${max}` : null"
        class="text-field-3__input"
        :aria-labelledby="props.fieldName"
        :aria-describedby="`${props.fieldName}-message`"
        :aria-invalid="error ? 'true' : 'false'"
        @focus.passive="onFocus"
        @blur.passive="onBlur"
      >
```

**Comment by userquin** [comment]
Ok, changing 2 things works, but still necessary to clear data:

1. Removed v-model on page:
```html
<template>
  <form class="caracterizacion-v1" @submit.prevent="submit">
    <div class="inputs">
      <AppTextField3
        field-name="primerNombre"
        :validation="form"
      />
```
2. Removed model from SFC and converter to computed and adjust dirty to use it from validator object:
```typescript
const props = defineProps({
  fieldName: {
    type: String,
    required: true,
  },
  validation: {
    type: Object,
    required: true,
  },
  requiredMark: {
    type: String,
    default: '(*)',
  },
})

const focused = ref(false)
const floating = ref(false)
const touched = ref(false)

const fieldValidation = computed(() => {
  return props.validation[props.fieldName]
})
const internalValue = computed(() => {
  return fieldValidation.value.$value
})
...
const dirty = computed(() => {
  return /* touched.value || */fieldValidation.value.$dirty
})

```

and just set the v-model of the input pointing to `$value`:
```html
      <input
        v-model="fieldValidation.$value"
        type="text"
        :maxlength="max ? `${max}` : null"
        class="text-field-3__input"
        :aria-labelledby="props.fieldName"
        :aria-describedby="`${props.fieldName}-message`"
        :aria-invalid="error ? 'true' : 'false'"
        @focus.passive="onFocus"
        @blur.passive="onBlur"
      >
```

**Comment by userquin** [comment]
So, I can set $dirty=false and problem solved?

**Comment by userquin** [comment]
There is no way, I have tried all possible combinations, finally I just recreate the object as you suggest...

thx
