### ISSUE TITLE
debounce type is being exported but with no function

### ISSUE THREAD

**Issue by MechJosh0** [pikax/vue-composable#743]
The function `debounce` is exported and available according to Typescript but the variable is `undefined` when used. I assume the type of the function is being exported but not the function itself, with the type being exported in error.

**Comment by pikax** [comment]
It should be available and work 🤔 

Can you provide a repo?

**Comment by MechJosh0** [comment]
Ah, it is working :) My fault, sorry.

My issue was I'm building a component/composable library and forgot to list `vue-composable` as an external dependency so it was being built correctly and nothing from `vue-composable` was being made available in the main project. `debounce` was the only one I tested (due to naming conflict) and because it wasn't documented I thought it was exported in error.

**Comment by pikax** [comment]
Is not documented because is being used by `useDebounce` and `debouncedRef`, I expose the internals because I use them in my other projects with vue-composable 😄
