### ISSUE TITLE
How to reset the form after submit and keep the validation

### ISSUE THREAD

**Issue by felipe-muner** [pikax/vue-composable#753]
Hello my friends...

I'm using vue-composable and everything is going well I did many different forms following the [explanation](https://pikax.me/vue-composable/composable/validation/validation.html)..

My issue is how could I reset the form and keep the validation(very important)...

when i follow the code:

```
function buildValidation(){
  return useValidation({....})
}

const form = ref(buildValidation());

function submit(){
 form.value = buildValidation()
}

```

 it works fine

but I don't know how to print the errors if some of them are invalid.

I had this before to print the errors:

```
   const errorMessage = field =>
   form[field].$dirty && form[field].$anyInvalid ? form[field].$errors[0] : ''
   
   <v-field type="is-danger" label="Name" :message="errorMessage('name')" for="name">
      <v-input type="text" id="name" v-model="form.name.$value" />
    </v-field>
```

 but I still don't know how to combine it...
 
 thank you in advance

**Comment by pikax** [comment]
Added `$touch/$reset` functions which will allow you to update the `$dirty`

**Comment by negezor** [comment]
The $dirty change will only happen once, after $reset() it won't work anymore.

https://github.com/pikax/vue-composable/blob/c7e795461a928ab6c649e710279f8634ad34a05a/packages/vue-composable/src/validation/validation.ts#L239-L246
