### ISSUE TITLE
useLocalStorage could accept ref as a key

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [pikax/vue-composable#776]
Now it accepts only strings:

```js
function useLocalStorage(key: string, ...
```

If the key is dynamic one should be able to do the following:

```js
const { storage } = useLocalStorage(toRef(props, 'key'));
```

That would of course apply to other similar composables (`useSessionStorage` etc) as well  as those not related to the storage, ex.
```js
export declare function useLockScroll(selector: string, ...
export declare function useMatchMedia(query: string, ...
```
but it's ok if that issue is only for `useLocalStorage`

**Comment by pikax** [comment]
What should be the expected behaviour if the `localStorage` has already a value with that key, do we update the value ref to the localStorage value or do we update the localStorage value to the same has the ref value?

On a first thought the other composables would be save to use ref key

**Comment by jacekkarczmarczyk** [comment]
IMHO it should update the value ref to the localStorage. 

Let me show the (close to) real life example: there's a list of Foo items with pagination and possibility of choosing how many items per page are displayed, that value is stored in LS, and there's also list of Bar items with the same functionality, using the same component but with different `:type="'Foo' | 'Bar'"` prop, and there's a switch between Foo and Bar, when I change from 'Foo' to 'Bar' I'd expect to load the items per page value for 'Bar' type from LS instead of setting 'Bar's storage value to the one that was chosen for 'Foo'
