### ISSUE TITLE
Use both vue-composable and any cjs module (such as vuedraggable)  in vite, resulting in an error!

### ISSUE THREAD

**Issue by shufangyi** [pikax/vue-composable#852]
In [vue-composable.esm-bundler.js]

if change

```
import {...} from '@vue/runtime-core';
```

to
```
import {...} from 'vue';
```

then
```
yarn dev --force
```

this error will be solved!

example 👉  [link](https://github.com/shufangyi/vite-vue/tree/show-vue-composable-error)

**Comment by pikax** [comment]
Can't open your example link, maybe is private, do you mind making public?

**Comment by shufangyi** [comment]
My mis! Now its public!

**Comment by pikax** [comment]
After talking with @patak-js this issue can be solved by adding `dedup` to `vite.config`

```ts
import path from "path";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import vueJsx from "@vitejs/plugin-vue-jsx";
import pages from "vite-plugin-pages";

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    dedupe: ["vue"], // dedup vue
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
  plugins: [
    vue(),
    // options are passed on to @vue/babel-plugin-jsx
    vueJsx({}),
    pages({
      syncIndex: false,
      extensions: ["vue", "ts"],
    }),
  ],
});
```

> Sometimes there are issues though if there are duplicated copies of the same dep, and you need to explicitely dedupe them.

**Comment by shufangyi** [comment]
I have tried the configure `dedupe: ["vue"]`.
Somehow it doesnot work...😢

**Comment by pikax** [comment]
That's odd, I've this working here: 
[vite-vue-show-vue-composable-error.zip](https://github.com/pikax/vue-composable/files/6329321/vite-vue-show-vue-composable-error.zip)

I've deleted the `node_modules` and try it again, and couldn't see the error, do you mind try it again?

**Comment by shufangyi** [comment]
I even restart my comput...

the same error -> [image](https://drive.google.com/file/d/1ij2u_18_0614ot7eFyMLBp8p7g1-aPJ_/view?usp=sharing)

**Comment by shufangyi** [comment]
I downloaded the zip file you provided.
 - yarn
 - yarn dev --force

**Comment by jcppman** [comment]
Same here.

Tried the example @pikax provided and it can render the page correctly but once I drag any item this throws:

```
vue.runtime.esm-bundler.js:1 Uncaught ReferenceError: nextTick is not defined
    at Object.nextTick (vue.runtime.esm-bundler.js:1)
    at Proxy._emit (vuedraggable.js:14)
    at Sortable.<anonymous> (vuedraggable.js:29)
    at dispatchEvent (sortable.esm.js:916)
    at _dispatchEvent (sortable.esm.js:961)
    at Sortable._dragStarted (sortable.esm.js:1570)
```

## My env:
- node v15.5.0
- yarn v1.22.10
- chrome 89.0.4389.128 (Official Build) (x86_64)

**Comment by CalebKester** [comment]
Just putting this here as a followup. I was running into the issue as I think it was similar to what's being reported here. Or maybe it's related to the dedupe vite fix. Anyways, I was trying to get vue-composable to work in yarn workspace (monorepo) and was running into the error. Eventually I fixed it by installing @next which looks like it's `1.0.0-alpha.37` I'm not sure why that worked and beta.37 doesn't. I'm more then happy to provide any sort of testing or lookup into this. I just thought it was strange that upgrading to that version seemed to fix my issue.

```Error: Build failed with 1 error:
../node_modules/vue-composable/dist/vue-composable.esm-bundler.js:1:120: error: Could not resolve "@vue/composition-api" (mark it as external to exclude it from the bundle)```
